server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://192.168.8.139:3306/smartqa
    username: root
    password: 123456
#    password: password
    driver-class-name : com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

